services:
  order-service:
    image: order-service:latest
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fcfs?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://admin:1234@eureka-server:8761/eureka/
    ports:
      - "8082:8082"
    networks:
      - docker-cons

  product-service:
    image: product-service:latest
    container_name: product-service
    build:
      context: ./product-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fcfs?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://admin:1234@eureka-server:8761/eureka/
    ports:
      - "8081:8081"
    networks:
      - docker-cons

  user-service:
    image: user-service:latest
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fcfs?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://admin:1234@eureka-server:8761/eureka/
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "8080:8080"
    networks:
      - docker-cons

volumes:
  mysql-data:

networks:
  docker-cons:
    driver: bridge